name: build

on:
  workflow_dispatch:
    inputs:
      build:
        description: " Build process "
        required: true
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Envirment
      uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 18
    - uses: actions/setup-python@v5
      with:
        python-version: '3.13' 
    - run: |
        python -m pip install afdko
        sudo apt-get update
        sudo apt-get install ttfautohint

    - name: Build
      shell: bash
      run: |
        npm install
        npm run build ttf
        
    


    


       
    
  
